version: "3.1"

services:
  layout-propaganda:
    image: node:20.9.0
    container_name: layout-propaganda
    restart: always
    depends_on:
      - layout-propaganda-database
    ports:
      - 3333:3333
      - 5555:5555
    volumes:
      - .:/home/app
    working_dir: /home/app
    command: ["sh", "-c", 
      "yarn prisma migrate deploy && yarn prisma studio & yarn dev"
    ]

  layout-propaganda-database:
    container_name: layout-propaganda-database
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./.docker/database:/var/lib/postgresql/data
